### ISSUE TITLE
Checkboxes can no longer be resized using CSS on Windows at default OS DPI

### ISSUE THREAD

**Issue by 36degrees** [alphagov/reported-bugs#21]
**Upstream bug:** https://bugzilla.mozilla.org/show_bug.cgi?id=446511#c9
**Date:** 2015-09-01
**Reported by:** Robin Whittleton (@robinwhittleton)

---

### Overview

[Robin] did some research on how radios and checkboxes resize in various browsers: https://gdstechnology.blog.gov.uk/2015/08/27/making-radio-buttons-and-checkboxes-easier-to-use/

Firefox on Windows is the sole browser on Windows 10 that I tested that still doesn’t let you resize checkboxes/radios. Everyone else either users the vector system widgets (IE, Edge), what appear to be built-in but still vector widgets (Chrome) or if you’re Opera Windows Classic widgets(?!).

It’d be lovely if Firefox could fix this regression. At the moment our alternative is to hand-roll custom radios / checkboxes with all of the difficulty of maintenance that brings.

Firefox on Windows 10: https://gdstechnology.blog.gov.uk/wp-content/uploads/sites/31/2015/08/win_10_firefox.png
IE11 on Windows 10: https://gdstechnology.blog.gov.uk/wp-content/uploads/sites/31/2015/08/win_10_ie11.png
Edge on Windows 10: https://gdstechnology.blog.gov.uk/wp-content/uploads/sites/31/2015/08/win_10_edge.png
Chrome on Windows 10: https://gdstechnology.blog.gov.uk/wp-content/uploads/sites/31/2015/08/win_10_chrome.png
Opera on Windows 10: https://gdstechnology.blog.gov.uk/wp-content/uploads/sites/31/2015/08/win_10_opera.png

**Comment by jrmuizel** [comment]
The upstream bug has been resolved fixed.
