### ISSUE TITLE
Consider hand-rolling radios and checkboxes for resizability

### ISSUE THREAD

**Issue by 36degrees** [alphagov/reported-bugs#24]
**Upstream bug:** https://bugzilla.mozilla.org/show_bug.cgi?id=1200559
**Date:** 2015-09-01
**Reported by:** Robin Whittleton (@robinwhittleton)

---

### Overview

In bug 394892 Markus Stange fixed radios and checkboxes to use native Cocoa widgets and made them resizable, which puts Firefox a step up from where Chrome and Safari currently are. It’s a shame though that they look pixellated at large sizes (see attached image).

![osx_10 10_firefox](https://user-images.githubusercontent.com/121939/58713137-e7a43e80-83b9-11e9-8582-9ef4af55f097.png)

In the intervening time an @2x set of image states for checkboxes and radios has been introduced (try setting transform:scale(2); against an input in Chrome or Safari) which would be a stop-gap, but it would be very nice if this could be resolution independent.

Other browsers (for example Chrome on Windows) have their own set of vector widgets including checkboxes and radios. Is this something Mozilla would be interested in doing? It would obviously be better if OS X introduced resolution independent controls and I’d imagine it can’t be far off, so that might be the better path.

**Comment by jrmuizel** [comment]
The upstream bug has been fixed.

**Comment by 36degrees** [comment]
@jrmuizel thanks!
