### ISSUE TITLE
NVDA reports inputs of `type="number"` as unlabeled in the 'forms' elements list

### ISSUE THREAD

**Issue by 36degrees** [alphagov/reported-bugs#41]
**Upstream bug:** https://github.com/nvaccess/nvda/issues/9675
**Date:** 2019-06-05
**Reported by:** Oliver Byford
**Related to:** https://github.com/alphagov/govuk-frontend/issues/1408

---

### Steps to reproduce:

With an HTML document containing the following markup, open the elements list using NVDA + F7 and select the 'Form fields' type.

```html
<input type="text" id="text-field">
<label for="text-field">Text field</label>

<br><br>

<input type="number" id="number-field">
<label for="number-field">Number field</label>
```

([View in Codepen](https://codepen.io/36degrees/pen/joJovN))

### Actual behavior:

The elements list does not include the text from the label associated with the number field; instead reporting it as 'unlabeled':

- Text field; edit; has autocomplete
- Unlabeled; edit

<img width="1136" alt="Screen Shot 2019-06-05 at 13 23 01" src="https://user-images.githubusercontent.com/121939/58956489-560c4680-8796-11e9-9a78-9f4487e568b5.png">

### Expected behavior:

The elements list should include both fields with the text from the associated label:

- Text field; edit; has autocomplete
- Number field; edit

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.1.1

#### Windows version:

Windows 10; Version 1607; Build 14393. (VirtualBox VM)

#### Name and version of other software in use when reproducing the issue:

Firefox 67.0.1

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

N/A

**Comment by tigt** [comment]
It looks like this issue is fixed as of Firefox 74, according to https://github.com/nvaccess/nvda/issues/9675#issuecomment-592997952
