### ISSUE TITLE
JAWs incorrectly announces combobox input depending on how it is tabbed to

### ISSUE THREAD

**Issue by NickColley** [alphagov/reported-bugs#48]
**Upstream bug:** https://github.com/FreedomScientific/VFO-standards-support/issues/228
**Date:** 2019-07-30
**Reported by:** Nick Colley
**Related to:** https://github.com/alphagov/govuk-design-system/issues/938

---

### Overview

User feedback:

> When using JAWS, I navigated with the ‘Tab’ key and located a link which announced as ‘Search design system’. I selected the link and was taken directly to an autocomplete to search for a component.

Video demonstration in context on the Design System website: https://youtu.be/CFvk9W5hE0o

I've managed to reproduce this issue in Internet Explorer 11 and using JAWS 2018, it seems to be a bug with JAWS where the link's announcement is duplicated onto the input's announcement.

Tab to Design System home link
Announcement: "GOV.UK Design System link"
Tab to 'Search design system' input
Announcement: "Search design system visited link"
Shift tab to Design System home link
Announcement: "GOV.UK Design System link"
Tab to 'Search design system' input
Announcement: "Search design system edit combo [...]"

This does not happen when tabbing away from the input and tabbing back towards in the input.

When removing the `[role=combobox]` wrapper, the problem no longer exists.

Minimal markup to reproduce the issue:

```html
<a href="/">Home</a>
<label for="username">Username</label>
<div role="combobox">
  <input id="username">
</div>
```

### Expected result

When tabbing to the input it is announced correctly.

### Actual result

When tabbing to the input it is announced as the previous announcement, in this case it is announced as the previous link.

**Comment by 36degrees** [comment]
> "Closing this as it appears to be an IE 11/JAWS bug and we are no longer supporting IE 11"
