### ISSUE TITLE
font-size property doesn't apply to Safari file upload button

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/reported-bugs#61]
**Upstream bug:** https://bugs.webkit.org/show_bug.cgi?id=224746
**Date:** 2021-04-19
**Reported by:** Vanita Barrett (via https://github.com/alphagov/govuk-frontend/issues/2194)
**Related to:** https://github.com/alphagov/govuk-frontend/issues/2194

---

### Overview

When applying the `font-size` property to a file upload input, the font-size of the file upload button does not change. This happens even when applying the font-size property using the ::-webkit-file-upload-button selector.

### Expected result

`font-size` of the file upload button should change and match what's set in the CSS

### Actual result

`font-size` of the file upload button remains the same. The size of the 'no file selected' text does change, which pushes it out of alignment.

Strangely, the font-size does change when the file upload has a background-color applied using ::-webkit-file-upload-button.

**Comment by nt1m** [comment]
https://github.com/WebKit/WebKit/commit/1a0105921defca0770820813cdec1e805036c441 should fix this!

**Comment by 36degrees** [comment]
Fix included in [Safari Tech Preview 163](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/)
